# Deploy JS and coverage doc to master

name: CD
on:
  # Triggers the workflow on push to any branch
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-js-and-coverage-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          
      - name: Install modules
        run: npm --prefix source/ install 

      - name: Build coverage docs
        run: npm --prefix source/ test

      - name: Build JSDoc
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source/src/scripts
          output_dir: ./source/docs
          template: minami
          front_page: README.md

      - name: Commit Docs
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git status
          git commit -m "Update JSDocs & Jest coverage report" -a

      - name: Push Generated Docs
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #     publish_dir: ./source/docs
      
