# Run checks (tests, linting, etc.) on push

name: CI
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # installs the npm modules
      - name: Install modules
        run: npm --prefix source/ install

      # lint
      - name: Run linter
        run: npm --prefix source/ run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #installs the npm modules
      - name: Install modules
        run: npm --prefix source/ install

      # run the test suite
      - name: Run tests
        run: npm --prefix source/ test

      - name: Annotate tests on PR
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm --prefix source/ test"
