# Run checks (tests, linting, etc.) on push

name: Continuous Integration
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # installs the npm modules
      - name: Install modules
        run: npm --prefix source/ install 

      # run the test suite
      - name: Run tests
        run: npm --prefix source/ test